name: Beta Build

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    name: Build Beta
    runs-on: macos-26

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Build
        run: |
          make

      - name: Upload IPA Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Ksign-ipa
          path: packages/Ksign.ipa
          if-no-files-found: error
